### PR TITLE
Fix proctor link not displaying

### LINKED ISSUE #59: Proctor link is not getting displayed
## Description
Proctor link is not getting displayed 
**Current behavior**
Whenever options like due date are enabled, it doesn't display the proctor link

**Expected behavior**
proctor link should be available in all scenarios

## Steps to reproduce

assign attempt id as per the checkbox with its value

## Versions

- Moodle: 3.9
- Plugin: 3.1.3
- Browser: Chrome
- OS: MACOS

### PR DESCRIPTION
**Pull request by rohansharmasitoula**
## Description
- Included function to fetch appropriate attempt_id

## Github Issue
- Resolves #59 

## Checklist before requesting a review
- [x] One line description of the changes is added in the PR
- [x] Issue is linked to the PR via commits 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires only a documentation update

### CODE REVIEW

File: frame.php [hunk 1]
```diff
@@ -96,7 +96,7 @@ function startProview(
         previewStyle, 
         clear) {
         const referenceLinksArray = reference_link.split('\r\n').map(link => {
-            const [url, caption] = link.split(':');
+            const [url, caption] = link.split('::');
```
Comment (rakeshprabhu) [inline frame.php:99]: @rohansharmasitoula can we use markdown syntax for link data capturing?
\[Label\]\(url\)

**Review by rakeshprabhu — CHANGES_REQUESTED** [review]
Change the reference link format from :: to markdown link format.

File: frame.php (hunk 1 above)
Comment (rohansharmasitoula) [reply frame.php]: changed 
@rakeshprabhu

**Review by rakeshprabhu — APPROVED** [review]
