### PR TITLE
fixed proview_playback_url issue

### LINKED ISSUE #54: Proview_playback_url not updating for other instances
## The proview_playback_url was not updating for other instances other than EU

**Current behavior**
Whatever proview_playback_url was being added at configuration, the application is taking the EU proview_playback_url.
The playback_url was being generated as per the proview_url in the current code.

**Expected behavior**
proview_playback_url is supposed to be updated as per the entered configuration.

## Steps to reproduce

Remove the current url generation code which assigns proview_playback_url as per the proview_url and then take proview_playback_url as per the configuration

**Screenshots**
image

## Versions

- Moodle: 3.9
- Plugin: 3.1.0
- Browser: Chrome
- OS: MACos

### PR DESCRIPTION
**Pull request by rohansharmasitoula**
## Description
- Fixed playback_proview_url not being updated as per the configuration

## Github Issue
- resolves #54 

## Checklist before requesting a review
- [x] One line description of the changes is added in the PR
- [x] Issue is linked to the PR via commits (eg: resolves #123)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires only a documentation update

## Dependencies (if any):
- None

## References (if any):
- [ ] Any reference documents to review before/after this PR review
- [ ] None

### CODE REVIEW

File: version.php [hunk 1]
```diff
@@ -28,9 +28,9 @@
 
 defined('MOODLE_INTERNAL') || die;
 
-$plugin->version  = 2023081601;
+$plugin->version  = 2023082301;
 $plugin->requires = 2020061500;
-$plugin->release = '3.1.0 (Build: 2023081601)';
+$plugin->release = '3.1.0 (Build: 2023082301)';
```
Comment (devang1281) [inline version.php:33]: @rohansharmasitoula Update the build version to 3.1.1 and give the PR to a release branch

**Review by devang1281 — CHANGES_REQUESTED** [review]

File: version.php (hunk 1 above)
Comment (rohansharmasitoula) [reply version.php]: done

**Review by devang1281 — APPROVED** [review]
LGTM
